### PR TITLE
Change stuff to make it build

### PR DESCRIPTION
**Pull request by KonPet**
Removed the arm7 section
Changed the makefile to only use the arm9 stuff
Epicpkmn: Fix source/Graphics/GraphicsManager.cpp
Fixed the exception handler

### CODE REVIEW

**Comment by peppy** [comment]
Thanks for the contributions! I'm not really in a place I have the time or resources to confirm the code changes (and I'm pretty sure neither is @echojc), but am I able to compile this on a mac? Maybe it'd be fine to merge if we can confirm compilation.

**Comment by KonPet** [comment]
Yeah, compiling is quite easy. You just need to install DevKitPro with libnds and then run the `make` command in the osu-ds folder

**Comment by peppy** [comment]
The install process for devkitpro means I'll probably need to spin up a VM to give it a try. Not sure if/when I'll find time for this, but if someone else comes across this project/PR and manages to find success in these changes, I'm think I'd be happy to merge them in.

**Comment by ceIery** [comment]
hi! after installing devkitPro using the latest installer release available, i can verify that this pr compiled for me

image

**Comment by peppy** [comment]
@ceIery thanks for the confirmation.

I think I'll go ahead and merge this change. I've already got approval from @echojc to take action as required here, for what that's worth.

**Pull request merged**
